# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64

numpy
openai==1.9.0
pandas==2.1.4
python-dotenv==1.0.1
python==3.11
streamlit==1.31.1
