aiohttp @ file:///C:/b/abs_b78zt6vo64/croot/aiohttp_1694181126607/work
aiosignal @ file:///home/conda/feedstock_root/build_artifacts/aiosignal_1667935791922/work
altair==5.2.0
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1688651106312/work/dist
appdirs @ file:///home/conda/feedstock_root/build_artifacts/appdirs_1603108395799/work
async-timeout @ file:///home/conda/feedstock_root/build_artifacts/async-timeout_1691763562544/work
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1683424013410/work
backoff==2.2.1
bcrypt==4.0.1
blinker==1.7.0
Bottleneck @ file:///C:/ci_311/bottleneck_1676500016583/work
Brotli @ file:///C:/ci_311/brotli-split_1676435766766/work
cachetools @ file:///home/conda/feedstock_root/build_artifacts/cachetools_1688227447901/work
certifi @ file:///C:/b/abs_35d7n66oz9/croot/certifi_1707229248467/work/certifi
cffi @ file:///C:/ci_311/cffi_1676423759166/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1688813409104/work
chroma-hnswlib==0.7.3
chromadb==0.4.13
click @ file:///D:/bld/click_1692312014553/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
coloredlogs==15.0.1
contourpy @ file:///C:/ci_311/contourpy_1676431756017/work
cryptography @ file:///C:/b/abs_f4do8t8jfs/croot/cryptography_1694444424531/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
dataclasses @ file:///home/conda/feedstock_root/build_artifacts/dataclasses_1628958434797/work
dataclasses-json @ file:///home/conda/feedstock_root/build_artifacts/dataclasses-json_1648489389285/work
distro==1.9.0
docker-pycreds==0.4.0
et-xmlfile @ file:///home/conda/feedstock_root/build_artifacts/et_xmlfile_1674664118162/work
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1692026125334/work
fastapi==0.103.1
filelock==3.12.4
flatbuffers==23.5.26
fonttools==4.25.0
frozenlist @ file:///C:/ci_311/frozenlist_1676428131576/work
fsspec==2023.9.2
gitdb @ file:///home/conda/feedstock_root/build_artifacts/gitdb_1669279893622/work
GitPython @ file:///home/conda/feedstock_root/build_artifacts/gitpython_1695397254077/work
google-api-core @ file:///home/conda/feedstock_root/build_artifacts/google-api-core-split_1695727073142/work
google-auth @ file:///home/conda/feedstock_root/build_artifacts/google-auth_1695791164185/work
googleapis-common-protos @ file:///home/conda/feedstock_root/build_artifacts/googleapis-common-protos-feedstock_1690830130005/work
greenlet @ file:///C:/ci_311/greenlet_1676436788118/work
h11==0.14.0
httpcore==1.0.4
httptools==0.6.0
httpx==0.27.0
huggingface-hub==0.16.4
humanfriendly==10.0
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
importlib-metadata==7.0.1
importlib-resources==6.1.0
Jinja2==3.1.3
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1691577114857/work
jsonpatch @ file:///home/conda/feedstock_root/build_artifacts/jsonpatch_1695536281965/work
jsonpointer @ file:///D:/bld/jsonpointer_1695397361610/work
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
kiwisolver @ file:///C:/ci_311/kiwisolver_1676431979301/work
langchain @ file:///home/conda/feedstock_root/build_artifacts/langchain_1695747954447/work
langsmith @ file:///home/conda/feedstock_root/build_artifacts/langsmith_1695794258752/work
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow @ file:///home/conda/feedstock_root/build_artifacts/marshmallow_1689924608696/work
marshmallow-enum @ file:///home/conda/feedstock_root/build_artifacts/marshmallow-enum_1602427317752/work
matplotlib @ file:///C:/ci_311/matplotlib-suite_1676500808038/work
mdurl==0.1.2
mkl-fft @ file:///C:/b/abs_19i1y8ykas/croot/mkl_fft_1695058226480/work
mkl-random @ file:///C:/b/abs_edwkj1_o69/croot/mkl_random_1695059866750/work
mkl-service==2.4.0
monotonic==1.6
mpmath==1.3.0
multidict @ file:///C:/ci_311/multidict_1676428396308/work
munkres==1.1.4
mypy-extensions @ file:///home/conda/feedstock_root/build_artifacts/mypy_extensions_1675543315189/work
numexpr @ file:///C:/b/abs_afm0oewmmt/croot/numexpr_1683221839116/work
numpy @ file:///C:/b/abs_f6napi3n6e/croot/numpy_and_numpy_base_1691091651337/work
onnxruntime==1.16.0
openai==1.12.0
openapi-schema-pydantic @ file:///home/conda/feedstock_root/build_artifacts/openapi-schema-pydantic_1681130872959/work
openpyxl @ file:///home/conda/feedstock_root/build_artifacts/openpyxl_1632332968451/work
overrides==7.4.0
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pandas @ file:///C:/miniconda3/conda-bld/pandas_1692298018988/work
pandas-stubs @ file:///home/conda/feedstock_root/build_artifacts/pandas-stubs_1692034042688/work
pathtools==0.1.2
Pillow @ file:///C:/b/abs_153xikw91n/croot/pillow_1695134603563/work
plotly @ file:///home/conda/feedstock_root/build_artifacts/plotly_1694802097009/work
posthog==3.0.2
protobuf @ file:///D:/bld/protobuf_1681050297321/work/python
psutil @ file:///C:/ci_311_rebuilds/psutil_1679005906571/work
pulsar-client==3.3.0
pyarrow==15.0.0
pyasn1 @ file:///home/conda/feedstock_root/build_artifacts/pyasn1_1694615621498/work
pyasn1-modules @ file:///home/conda/feedstock_root/build_artifacts/pyasn1-modules_1695107857548/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pydantic @ file:///C:/b/abs_9byjrk31gl/croot/pydantic_1695798904828/work
pydeck==0.8.1b0
Pygments==2.17.2
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1685514481738/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1690737849915/work
pypdf @ file:///home/conda/feedstock_root/build_artifacts/pypdf-split_1695589880351/work/dist
PyPDF2 @ file:///home/conda/feedstock_root/build_artifacts/pypdf2_1667024492624/work
PyPika==0.48.9
pyreadline3==3.4.1
PySocks @ file:///D:/bld/pysocks_1661604991356/work
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-dotenv==1.0.0
pytz @ file:///C:/b/abs_19q3ljkez4/croot/pytz_1695131651401/work
pyu2f @ file:///home/conda/feedstock_root/build_artifacts/pyu2f_1604248910016/work
PyYAML @ file:///C:/ci_311/pyyaml_1676432488822/work
referencing==0.33.0
regex==2023.8.8
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1684774241324/work
rich==13.7.0
rpds-py==0.18.0
rsa @ file:///home/conda/feedstock_root/build_artifacts/rsa_1658328885051/work
scikit-learn @ file:///C:/b/abs_38k7ridbgr/croot/scikit-learn_1684954723009/work
scipy==1.11.1
sentry-sdk @ file:///home/conda/feedstock_root/build_artifacts/sentry-sdk_1694613615724/work
setproctitle @ file:///C:/ci_311/setproctitle_1676493165619/work
six @ file:///tmp/build/80754af9/six_1644875935023/work
smmap @ file:///home/conda/feedstock_root/build_artifacts/smmap_1611376390914/work
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1662051266223/work
SQLAlchemy @ file:///C:/b/abs_d3tao6jnck/croot/sqlalchemy_1695720955292/work
starlette==0.27.0
streamlit==1.31.1
stringcase==1.2.0
sympy==1.12
tenacity @ file:///home/conda/feedstock_root/build_artifacts/tenacity_1692026804430/work
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1689261241048/work
tiktoken==0.5.1
tokenizers==0.14.0
toml==0.10.2
toolz==0.12.1
tornado==6.4
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1691671248568/work
typer==0.9.0
types-pytz @ file:///home/conda/feedstock_root/build_artifacts/types-pytz_1695236566539/work
typing-inspect @ file:///home/conda/feedstock_root/build_artifacts/typing_inspect_1685820062773/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1695040754690/work
tzdata @ file:///croot/python-tzdata_1690578112552/work
tzlocal==5.2
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1695228328709/work
uvicorn==0.23.2
validators==0.22.0
wandb @ file:///home/conda/feedstock_root/build_artifacts/wandb_1695391863777/work
watchdog==4.0.0
watchfiles==0.20.0
websockets==11.0.3
win-inet-pton @ file:///D:/bld/win_inet_pton_1667051142467/work
yarl @ file:///C:/ci_311/yarl_1676432870023/work
zipp==3.17.0
